### PR TITLE
Improve IRC layout for SchildiChat

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/SchildiChat/matrix-react-sdk/pull/21

This PR is essentially a retry of https://github.com/SchildiChat/matrix-react-sdk/pull/21 and intends to improve the IRC layout for SchildiChat, fixing several [issues](https://github.com/element-hq/element-web/labels/A-IRC-Layout) logged on the upstream repository as well. For detailed explanation, please check the superseded PR of mine.

As I am not quite sure of the workflow for the lite branch yet, please let me know what else to be done (for example, is creating a PR for `matrix-react-sdk` with the commit necessary?)

| |Upstream|SC|
|-|--------------|----|
|Message Panel|||
|Hidden event via Devtools|||
|Alignment|||

https://github.com/user-attachments/assets/e375631b-3041-4af1-9232-a6badda58cbb

https://github.com/user-attachments/assets/d302a60e-b560-47d1-bd68-7d500f1aa7bd

### CODE REVIEW

**Comment by luixxiul** [comment]
Please feel free to add edits as needed :)

**Comment by SpiritCroc** [comment]
Some quick notes without having looked into these in detail yet:

- qg / su-ex is our timeline layout CSS expert and still busy with life, so *maybe* I take a look at it and drop it as soon as any conflict arises, but I certainly will not maintain this in the long run (I don't use IRC layout after all). I assume it's fine that if whenever I drop it, you rebase it... not sure, the workflow hasn't been thought out yet and will require coordinating with su-ex.
- It just came to my attention that matrix-react-sdk was merged with the element-web repo upstream (finally), which means that I need to redo some patching *again*... hopefully later this week, but no guarantees. Until then I won't accept any PRs for sure, so you'll probably need to rebase then as well.

**Comment by luixxiul** [comment]
> qg / su-ex is our timeline layout CSS expert and still busy with life, so maybe I take a look at it and drop it as soon as any conflict arises, but I certainly will not maintain this in the long run (I don't use IRC layout after all). 

FWIW the actual code related to the IRC layout and EventTile on the upstream has been mostly created by [me](https://github.com/element-hq/element-web/blame/491f0cd08a2bc17f0ed3366de14b55ad2d5f597e/res/css/views/rooms/_EventTile.pcss#L270-L467), and apparently the file itself has not been quite changed since a couple of years, so I assume this PR will not create a huge conflict once rebasing is completed, unless the upstream will decide to replace the current UI as a whole for some reason.

> matrix-react-sdk was merged with the element-web repo upstream (finally)

Honestly I could not really understand what has been the intention of having it managed under Matrix Foundation in the first place...

**Comment by SpiritCroc** [comment]
> FWIW the actual code related to the IRC layout and EventTile on the upstream has been mostly created by [me](https://github.com/element-hq/element-web/blame/491f0cd08a2bc17f0ed3366de14b55ad2d5f597e/res/css/views/rooms/_EventTile.pcss#L270-L467), and apparently the file itself has not been quite changed since a couple of years, so I assume this PR will not create a huge conflict once rebasing is completed, unless the upstream will decide to replace the current UI as a whole for some reason.

Cool, good to know!

**Comment by luixxiul** [comment]
I noticed this would break alignment of emote messages. Fixing it.

**Comment by luixxiul** [comment]
I've closed the PR accidentally. Will create another one.

**Pull request closed without merging**
